### ISSUE TITLE
"Copy to Clipboard": only for root element 

### ISSUE THREAD

**Issue by bzemms** [mac-s-g/react-json-view#179]
Hi, 
Please add an option to customize on which level to present the "copy to clipboard" icon 
e.g: on on root or a number as done for the collapse option

**Comment by mac-s-g** [comment]
@bzemms I like this idea.  I'll apply "feature request" label.

**Comment by tnrich** [comment]
Anyone have a solution in user-land? Thanks!

**Comment by tnrich** [comment]
This is about as ugly as they come but works for now: 

```css
.react-json-view .copy-to-clipboard-container {
  display: none!important;
}
.react-json-view  >*>*>*>*>*>.copy-to-clipboard-container {
  display: inline-block!important;
}
```
